server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /payments/**, 
        - id: restaurant
          uri: http://localhost:8082
          predicates:
            - Path=/restaurants/**, 
        - id: delivery
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**, 
        - id: kakaotalk
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: index
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://front:8080
          predicates:
            - Path=/orders/**, /payments/**, 
        - id: restaurant
          uri: http://restaurant:8080
          predicates:
            - Path=/restaurants/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, 
        - id: kakaotalk
          uri: http://kakaotalk:8080
          predicates:
            - Path=, 
        - id: index
          uri: http://index:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
